/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formlar;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFrame;

/**
 *
 * @author asus
 */
public class TwoPanel extends javax.swing.JFrame {

    sunucu kaptan;
    ArrayList<GemiList> gemilerim;
    ArrayList<GemiList> onungemileri;
    String nick, nick2;
    String ip;
    SecimButton btn,test;
    SeninLabel label;
    ArrayList<SeninLabel> tumlabeller;

    /**
     * Creates new form TwoPanel
     */
    public TwoPanel(ArrayList<GemiList> gemilerim, String nick, String ip) {
        initComponents();
        this.setLocation(480, 100);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setSize(1200, 750);
        this.gemilerim = gemilerim;
        this.nick = nick;
        this.ip = ip;
        tumlabeller = new ArrayList<>();
        onungemileri = new ArrayList<>();
        kaptan = new sunucu();
        kaptan.sunucuac();
        for (int x = 0; x < 10; x++) {  //buton dizilimi için matris yapsı oluşturulup iç içe döngü yapıldı
            for (int y = 0; y < 10; y++) {
                btn = new SecimButton(x, y);
                label = new SeninLabel(x, y);
                tumlabeller.add(label);
                koordkoy(label);
                jPanel2.add(btn);
                seninpanel.add(label);

                btn.addMouseListener(new MouseAdapter() {  //mause tıklama eventi butonlara eklendi

                    @Override
                    public void mouseClicked(MouseEvent e) {
                        test = (SecimButton) e.getComponent();
                        if(kaptan.bagliMiyiz());
                         paketyolla(test);
                    }
                });
            }
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblonunad = new java.awt.Label();
        lblseninad = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        seninpanel = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblonunad.setAlignment(java.awt.Label.RIGHT);
        lblonunad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblonunad.setText("label1");

        lblseninad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblseninad.setText("label1");

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new java.awt.GridLayout(10, 10));

        jLabel1.setText("Oyuncu 1 :");

        jLabel2.setText(":  Oyuncu 2");

        seninpanel.setBackground(new java.awt.Color(0, 153, 153));
        seninpanel.setLayout(new java.awt.GridLayout(10, 10));

        jToggleButton1.setText("baglan");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(seninpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblseninad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblonunad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(lblseninad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblonunad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jToggleButton1)))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seninpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()) {

            Paket paket = new Paket();
            paket.setNick(nick);
            paket.setArr(gemilerim);
            kaptan.veriopen(paket);

            String baslangicStringi = kaptan.verial();
            String[] parts = baslangicStringi.split("-");

            this.nick2 = parts[0];
            for (int i = 1; i < parts.length; i = i + 2) {
                GemiList gemi = new GemiList();
                gemi.a = Integer.valueOf(parts[i]);
                gemi.b = Integer.valueOf(parts[i + 1]);
                onungemileri.add(gemi);

            }
            lblonunad.setText(nick2);
            lblseninad.setText(nick);

        } else {
            kaptan.sunucuyuKapa();

        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.Label lblonunad;
    private java.awt.Label lblseninad;
    private javax.swing.JPanel seninpanel;
    // End of variables declaration//GEN-END:variables

    private void koordkoy(SeninLabel label) {
        System.out.println("gemileri diz");
        Iterator<GemiList> iter = gemilerim.iterator();
        while (iter.hasNext()) {

            GemiList gemi = iter.next();

            if (gemi.a == label.idx && gemi.b == label.idy) {
                label.setBackground(Color.orange);
            }

        }
    }

    private void paketyolla(SecimButton test) {

          
        
        Paket secilen =new Paket();
        secilen.setKoordx(test.idx);
        secilen.setKoordx(test.idy);
        guncelle(secilen);
        kaptan.verigonder(secilen);
        
        String yolstring;
         Paket secilen2 =new Paket();   
         yolstring =kaptan.verial();
        String[] parts = yolstring.split("-");
        secilen2.setKoordx(Integer.valueOf(parts[0]));
        secilen2.setKoordy(Integer.valueOf(parts[1]));
        setrenk(secilen2);
        

        

        
    }
    private void guncelle(Paket paket) {
        Iterator<GemiList> iter = onungemileri.iterator();
       
        while (iter.hasNext()) {

            GemiList currentgemi = iter.next();

            if (currentgemi.a == paket.getKoordx()&& currentgemi.b == paket.getKoordy()) {

                test.setBackground(Color.BLACK);
                 test.setEnabled(false);

            }

        }
       test.setBackground(Color.YELLOW);
    }
            private void setrenk(Paket paket) {
 
        SeninLabel sl=labelimibul(paket);
        
        
        
            Iterator<GemiList> iter = gemilerim.iterator();
       
        while (iter.hasNext()) {

            GemiList currentgemi = iter.next();

            if (currentgemi.a == sl.idx && currentgemi.b ==sl.idy) {

                sl.setBackground(Color.BLACK);
                 sl.setEnabled(false);

            }
              sl.setBackground(Color.YELLOW);
        }    
        
   
    }
    
            private SeninLabel labelimibul(Paket paket) {
        Iterator<SeninLabel> iter = tumlabeller.iterator();
       
        while (iter.hasNext()) {

            SeninLabel currentlabel = iter.next();

            if (currentlabel.idx == paket.getKoordx()&& currentlabel.idy == paket.getKoordy()) {

               return currentlabel;

            }

        }
       return null;
    }
}
